### ISSUE TITLE
[degrade] mc is not able to upload a file from different clusters endpoints in federation setup

### ISSUE THREAD

**Issue by ahmedabt** [minio/mc#2618]
## Expected behavior
mc should be able to upload the files from any minio endpoint in federation setup which was the case in previous mc releases.

## Actual behavior
./mc cp modem_log.istp cluster1/bucket_in_cluster2/
mc: <ERROR> Failed to copy `file.dummy`. Bucket `bucket_in_cluster2` does not exist.

## Steps to reproduce the behavior
1) Start Minio in a federation setup with at least 2 clusters
2) use mc to upload a file to a bucket in cluser2 via cluster1 endpoint.

## mc version

Failing version:
mc version RELEASE.2018-11-30T01-52-08Z

Passing version: Version:
Version: 2018-11-06T01:12:20Z
Release-tag: RELEASE.2018-11-06T01-12-20Z
Commit-id: b827fac6356f80354a1cf61f43cf5e5b60bbb511

**Comment by ahmedabt** [comment]
@vadmeste: yes, it exists. the download scenario works fine using the same client. also, the upload scenario works fine with the old client on windows platform.

In the download scenario Linux platform "./mc cp modem_log.istp cluster1/bucket_in_cluster2/"
100.00 MB / 100.00 MB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00% 9.50 MB/s 10s

Using an older mc on windows "./mc cp modem_log.istp cluster1/bucket_in_cluster2/"
61.00 MB / 61.00 MB [======================================================================================================================================================] 100.00% 3.96 MB/s 15s

**Comment by vadmeste** [comment]
@ahmedabt I am not able to reproduce this, here is how I tested:

docker-compose.yaml

```
version: '3'
services:
  
  minio-server-muc:
    image: minio/minio:latest
    ports:
      - 80:80
    volumes:
      - minio-server_muc_demo4_data_vol:/data
      - minio-server_muc_demo4_logs_vol:/logs
    command: minio gateway --address :80 nas /data
    environment:
      - "MINIO_ACCESS_KEY=S2Q3CDB1FOPP24M9DGS2"
      - "MINIO_SECRET_KEY=EpIb-urpHW9rXNNdtHUS6X7SuElYXO-4b7k_H_ki"
      - "MINIO_HTTP_TRACE=/logs/http.log"
      - "MINIO_REGION=MUC"
      - "MINIO_ETCD_ENDPOINTS=http://etcd-server-muc:2379"
      - "MINIO_DOMAIN=tracecloud.test"
      - "MINIO_PUBLIC_IPS=172.18.0.2"
    networks:
      minio_network:
        ipv4_address: 172.18.0.2
  
  minio-server-sc:
    image: minio/minio:latest
    ports:
      - 90:80
    volumes:
      - minio-server_sc_demo4_data_vol:/data
      - minio-server_sc_demo4_logs_vol:/logs
    command: minio gateway --address :80 nas /data
    environment:
      - "MINIO_ACCESS_KEY=S2Q3CDB1FOPP24M9DGS2"
      - "MINIO_SECRET_KEY=EpIb-urpHW9rXNNdtHUS6X7SuElYXO-4b7k_H_ki"
      - "MINIO_HTTP_TRACE=/logs/http.log"
      - "MINIO_REGION=SC"
      - "MINIO_ETCD_ENDPOINTS=http://etcd-server-muc:2379"
      - "MINIO_DOMAIN=tracecloud.test"
      - "MINIO_PUBLIC_IPS=172.18.0.3"
    networks:
      minio_network:
        ipv4_address: 172.18.0.3

  etcd-server-muc:
    image: quay.io/coreos/etcd:v3.1.10
    ports:
      - 2379:2379
      - 2380:2380
    environment:
      - "ALLOW_NONE_AUTHENTICATION=yes"
      - "ETCD_ADVERTISE_CLIENT_URLS=http://etcd-server-muc:2379"
      - "ETCD_LISTEN_CLIENT_URLS=http://172.18.0.6:2379"
    networks:
      minio_network:
        ipv4_address: 172.18.0.6

volumes:
  minio-server_muc_demo4_data_vol:
  minio-server_muc_demo4_logs_vol:
  minio-server_sc_demo4_data_vol:
  minio-server_sc_demo4_logs_vol:

networks:
 minio_network:
   driver: bridge
   ipam:
    config:
      - subnet: 172.18.0.0/24
```

 ```
$ docker-compose -f docker-compose.yaml up
...
