### ISSUE TITLE
mc admin info crashes

### ISSUE THREAD

**Issue by Nepoxx** [minio/mc#2813]
## Expected behavior
`mc admin info alias` should return information on the `alias` instance
## Actual behavior
`mc admin info alias` crashes with the following stack trace (full output):

```
~> mc admin info myminioalias
●  minio0:9000
   Status : online
   Uptime : 6 hours
  Version : 2019-06-27T21:13:50Z
  Storage : Used 1.5 TiB
   Drives : 2/2 OK

●  minio1:9000
   Status : online
   Uptime : 3 hours
  Version : 2019-06-27T21:13:50Z
  Storage : Used 1.5 TiB
   Drives : 2/2 OK

panic: runtime error: index out of range

goroutine 1 [running]:
github.com/minio/mc/cmd.infoMessage.String(0x0, 0x0, 0x5558abb0c261, 0x2, 0xc00028fbe0, 0xb, 0x0, 0x0, 0xc00030cc60, 0x0, ...)
        /build/minio-client/src/go/src/github.com/minio/mc/cmd/admin-info.go:172 +0x15cc
github.com/minio/mc/cmd.printMsg(0x5558abf2e420, 0xc00055a1e0)
        /build/minio-client/src/go/src/github.com/minio/mc/cmd/print.go:30 +0xed
github.com/minio/mc/cmd.mainAdminInfo(0xc0002d6600, 0x0, 0x2d6600)
        /build/minio-client/src/go/src/github.com/minio/mc/cmd/admin-info.go:292 +0x766
github.com/minio/cli.HandleAction(0x5558abe06840, 0x5558abf13768, 0xc0002d6600, 0xc0002c8400, 0x0)
        /build/minio-client/src/go/pkg/mod/github.com/minio/cli@v1.20.0/app.go:526 +0xca
github.com/minio/cli.Command.Run(0x5558abb0d876, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x5558abb29295, 0x20, 0x0, ...)
        /build/minio-client/src/go/pkg/mod/github.com/minio/cli@v1.20.0/command.go:220 +0x998
github.com/minio/cli.(*App).RunAsSubcommand(0xc0001985a0, 0xc000087680, 0x0, 0x0)
        /build/minio-client/src/go/pkg/mod/github.com/minio/cli@v1.20.0/app.go:415 +0x817
github.com/minio/cli.Command.startApp(0x5558abb0e31f, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x5558abb1c189, 0x14, 0x0, ...)
        /build/minio-client/src/go/pkg/mod/github.com/minio/cli@v1.20.0/command.go:308 +0x815
github.com/minio/cli.Command.Run(0x5558abb0e31f, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x5558abb1c189, 0x14, 0x0, ...)
        /build/minio-client/src/go/pkg/mod/github.com/minio/cli@v1.20.0/command.go:106 +0x12a4
github.com/minio/cli.(*App).Run(0xc0001983c0, 0xc0000ac040, 0x4, 0x4, 0x0, 0x0)
        /build/minio-client/src/go/pkg/mod/github.com/minio/cli@v1.20.0/app.go:289 +0x6b1
github.com/minio/mc/cmd.Main(0xc0000ac040, 0x4, 0x4)
        /build/minio-client/src/go/src/github.com/minio/mc/cmd/main.go:102 +0x267
main.main()
        /build/minio-client/src/go/src/github.com/minio/mc/main.go:32 +0x47
```
## Steps to reproduce the behavior
This is a hard one. I currently have a faulty disk in my cluster. My faulty disk is mounted and some files/folders are accessible but most of the folders/files return a `ls: cannot access '...': Input/ouput error`

Here is my docker swarm compose file (take a look at `minio2`):

```yaml
version: '3.4'

x-default-deploy: &default-deploy
  replicas: 1
  restart_policy:
    condition: any
    delay: 10s
    window: 60s

x-venus-deploy: &venus-deploy
  <<: *default-deploy
  placement:
    constraints:
      - node.hostname == venus

x-mars-deploy: &mars-deploy
  <<: *default-deploy
  placement:
    constraints:
      - node.hostname == mars

x-minio-service: &minio-common
  image: minio/minio:RELEASE.2019-06-27T21-13-50Z
  networks:
    - minio_net
  logging:
    driver: json-file
    options:
      max-size: 50k
      max-file: 5
  environment:
    MINIO_ACCESS_KEY: {omitted}
    MINIO_SECRET_KEY: {omitted}
    # MINIO_STORAGE_CLASS_STANDARD: EC:4 # Default is N/2
    MINIO_STORAGE_CLASS_RRS: EC:2
  command: >
    server --compat
    http://minio0/export0 http://minio0/export1
    http://minio1/export0 http://minio1/export1
    http://minio2/export0 http://minio2/export1
    http://minio3/export0 http://minio3/export1
    http://minio4/export0 http://minio4/export1
    http://minio5/export0 http://minio5/export1

services:
  minio0:
    <<: *minio-common
    deploy: *venus-deploy
    hostname: minio0
    ports:
      - target: 9000
        published: 9001
        mode: host
    volumes:
      - "/minio/disk0/export:/export0"
      - "/minio/disk1/export:/export1"

  minio1:
    <<: *minio-common
    deploy: *venus-deploy
    hostname: minio1
    ports:
      - target: 9000
        published: 9002
        mode: host
    volumes:
      - "/minio/disk2/export:/export0"
      - "/minio/disk3/export:/export1"

  minio2:
    <<: *minio-common
    deploy: *venus-deploy
    hostname: minio2
    ports:
      - target: 9000
        published: 9003
        mode: host
    volumes:
      - "/minio/disk4/export:/export0" # <- This is the faulty disk #######################
      - "/minio/disk5/export:/export1"

  # Mars deployments
  minio3:
    <<: *minio-common
    deploy: *mars-deploy
    hostname: minio3
    ports:
      - target: 9000
        published: 9004
        mode: host
    volumes:
      - "/minio/disk0/export:/export0"
      - "/minio/disk1/export:/export1"

  minio4:
    <<: *minio-common
    deploy: *mars-deploy
    hostname: minio4
    ports:
      - target: 9000
        published: 9005
        mode: host
    volumes:
      - "/minio/disk2/export:/export0"
      - "/minio/disk3/export:/export1"

  minio5:
    <<: *minio-common
    deploy: *mars-deploy
    hostname: minio5
    ports:
      - target: 9000
        published: 9006
        mode: host
    volumes:
      - "/minio/disk4/export:/export0"
      - "/minio/disk5/export:/export1"

networks:
  minio_net:

```

Of course, if the disk is replaced by a non faulty disk, the problem goes away.

## mc version
- Version: 2019-06-12T20:35:20Z
Release-tag: RELEASE.2019-06-12T20-35-20Z
Commit-id: ca26dac8e2e7d2e9b2d888e82f9edbf0873b7d2e

## System information
Server:
- OS: Ubuntu 18.04.2 LTS
Kernel: Linux venus 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
Docker version 18.09.5, build e8ff056

Client:
OS: Arch (also tested on Ubuntu)
Linux {omitted} 5.1.15-arch1-1-ARCH #1 SMP PREEMPT Tue Jun 25 04:49:39 UTC 2019 x86_64 GNU/Linux
