### ISSUE TITLE
argo-artifacts-make-bucket-job fails at mkdir /etc/minio on OpenShift 4.2

### ISSUE THREAD

**Issue by dove-young** [minio/mc#3128]
`argo-artifacts-make-bucket-job` keep trying to `mkdir /etc/minio` but fails

`mc: <ERROR> Unable to save new mc config. mkdir /etc/minio: permission denied.`

Although it was said that it was fixed at https://github.com/minio/mc/issues/2640, but I still found it in helm chart 5.0.17.

```
apiVersion: v1
appVersion: master
description: MinIO is a high performance data infrastructure for machine learning,
  analytics and application data workloads.
home: https://min.io
icon: https://min.io/resources/img/logo/MINIO_wordmark.png
keywords:
- storage
- object-storage
- S3
maintainers:
- email: dev@minio.io
  name: Minio
- email: hello@acale.ph
  name: Acaleph
name: minio
sources:
- https://github.com/minio/minio
version: 5.0.17

```

it also fails even I bind sa `argo-artifacts` to `cluster-admin`.

`oc adm policy add-cluster-role-to-user cluster-admin -n argo-events -z argo-artifacts`

## mc --version
- (paste output of `mc --version`)
