### ISSUE TITLE
mc mirror : token too long

### ISSUE THREAD

**Issue by MaitreDede** [minio/mc#3296]
## Expected behavior

`mc mirror --watch` should perform without problems, handle the problems (restart sync), or crash properly.

## Actual behavior

`mc mirror --watch` prints error :
```
mc: <ERROR> Failed to perform mirroring. bufio.Scanner: token too long
```
but neither exits properly nor restart watching/sync. It stays stuck.

## Steps to reproduce the behavior

Launched as kubernetes deployment, to synchronise "same namespace" minio with "remote server" minio (through kubernetes ingress).

```yaml
    spec:
      containers:
        - args:
            - |
              mc config host add local http://minio-service:9000/ $MINIO_ACCESS_KEY $MINIO_SECRET_KEY
              mc config host add remote http://minio-service.remote-server.domain.tld:9000/ $MINIO_ACCESS_KEY $MINIO_SECRET_KEY
              mc mirror --watch --overwrite --remove --no-color local/movie/ remote/movie/
          command:
            - ash
            - -c
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: accessKey
                  name: minio-secret
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: secretKey
                  name: minio-secret
          image: minio/mc:RELEASE.2020-06-20T00-18-43Z
```

## mc --version
- mc version RELEASE.2020-06-20T00-18-43Z

## System information

Kubernetes 1.17.7, Docker image `minio/mc:RELEASE.2020-06-20T00-18-43Z`
