### ISSUE TITLE
Docker Image GitLab CI compatibility

### ISSUE THREAD

**Issue by StiviiK** [minio/mc#3362]
## Expected behavior
Docker Image should be useable for a step within GitLab CI

## Actual behavior
Job fails and the output displays the command help

## Steps to reproduce the behavior
```
deploy_cdn:
  image: minio/mc
  stage: deploy
  tags:
    - linux
    - dind
  script:
    - mc alias set test https://static.test.domain $MINIO_ACCESS_KEY $MINIO_SECRET_KEY
    - mc cp test.txt test/testbucket
```

**Comment by harshavardhana** [comment]
> deploy_cdn:
>   image: minio/mc
>   stage: deploy
>   tags:
>     - linux
>     - dind
>   script:
>     - mc alias set test https://static.test.domain $MINIO_ACCESS_KEY $MINIO_SECRET_KEY
>     - mc cp test.txt test/testbucket

This is wrong instead it should be 

> deploy_cdn:
>   image: minio/mc
>   stage: deploy
>   tags:
>     - linux
>     - dind
>   script:
>     - alias set test https://static.test.domain $MINIO_ACCESS_KEY $MINIO_SECRET_KEY
>     - cp test.txt test/testbucket

since `minio/mc` entrypoint is already `mc`

**Comment by StiviiK** [comment]
@harshavardhana it still fails with the same errors.
```
Restoring cache
00:02
Downloading artifacts
00:01
 Downloading artifacts for build_cdn_job (41088)...
 Downloading artifacts from coordinator... ok        id=41088 responseStatus=200 OK token=jCPCRyEv
Running before_script and script
00:02
 NAME:
   mc - MinIO Client for cloud storage and filesystems.
 USAGE:
   mc [FLAGS] COMMAND [COMMAND FLAGS | -h] [ARGUMENTS...]
 COMMANDS:
   alias      set, remove and list aliases in configuration file
   ls         list buckets and objects
   mb         make a bucket
   rb         remove a bucket
   cp         copy objects
   mirror     synchronize object(s) to a remote site
   cat        display object contents
   head       display first 'n' lines of an object
   pipe       stream STDIN to an object
   share      generate URL for temporary access to an object
   find       search for objects
   sql        run sql queries on objects
   stat       show object metadata
   mv         move objects
   tree       list buckets and objects in a tree format
   du         summarize disk usage recursively
   retention  set retention for object(s)
   legalhold  set legal hold for object(s)
   diff       list differences in object name, size, and date between two buckets
   rm         remove objects
   version    manage bucket versioning
   lock       manage default bucket object lock configuration
   ilm        manage bucket lifecycle
   encrypt    manage bucket encryption config
   event      manage object notifications
   watch      listen for object notification events
   policy     manage anonymous access to buckets and objects
   tag        manage tags for bucket(s) and object(s)
   replicate  configure server side bucket replication
   admin      manage MinIO servers
   update     update mc to latest release
   
 GLOBAL FLAGS:
   --autocompletion              install auto-completion for your shell
   --config-dir value, -C value  path to configuration folder (default: "/root/.mc")
   --quiet, -q                   disable progress bar display
   --no-color                    disable color theme
   --json                        enable JSON formatted output
   --debug                       enable debug output
   --insecure                    disable SSL certificate verification
   --help, -h                    show help
   --version, -v                 print the version
   
 TIP:
   Use 'mc --autocompletion' to enable shell autocompletion
 VERSION:
   RELEASE.2020-08-08T02-33-58Z
```

**Comment by harshavardhana** [comment]
We will document this the correct way to use it..

**Comment by s-thom** [comment]
I am also having this issue.

I have tried the following configurations in my `.gitlab-ci.yml`:

---

```yaml
deploy:
  image: minio/mc:latest
  stage: deploy
  script:
    - alias set minio $MINIO_HOST $MINIO_ACCESS_KEY $MINIO_SECRET_KEY
    - cp test.txt minio/bucket/destination.txt
```

This prints the help output and exists with code 1.

---

Based on the following except from the Docker Hub page, I tried setting the entrypoint in the yml file.

> Note: Above examples run `mc` against MinIO play environment by default. To run `mc` against other S3 compatible servers, start the container this way:
> 
> ```
> docker run -it --entrypoint=/bin/sh minio/mc
> ```

```yaml
deploy:
  image:
    name: minio/mc:latest
    entrypoint:
      - /bin/sh
  stage: deploy
  script:
    - alias set minio $MINIO_HOST $MINIO_ACCESS_KEY $MINIO_SECRET_KEY
    - cp test.txt minio/bucket/destination.txt
```

This errors with the message `/bin/sh: can't open 'sh': No such file or directory`.

---

I also tried setting the entrypoint to `/usr/bin/mc`, just in case.


```yaml
deploy:
  image:
    name: minio/mc:latest
    entrypoint:
      - /usr/bin/mc
  stage: deploy
  script:
    - alias set minio $MINIO_HOST $MINIO_ACCESS_KEY $MINIO_SECRET_KEY
    - cp test.txt minio/bucket/destination.txt
```

This had the same effect as the first attempt: help printed with error code 1.

---

I'm not sure where to proceed from here. If anyone has suggestions, I can try them and post results here.

**Comment by StiviiK** [comment]
My current Solution on this Issue, which is btw. very dirty, is using an the `appropriate/curl` image and downloading the `mc` binary manually. But I don't like this solution either.
```
deploy_cdn:
  image: appropriate/curl # minio/mc -- doesn't work correctly
  stage: deploy
  needs: ["build_cdn_job"]
  tags:
    - linux
    - dind
  script:
    - curl https://dl.min.io/client/mc/release/linux-amd64/mc --output mc
    - chmod +x mc
```

**Comment by s-thom** [comment]
I have done more investigation into this issue, and have found a solution that works using the `minio/mc` image.

```yaml
deploy:
  image:
    name: minio/mc
    entrypoint: [''] # <--- Use an empty string for your entrypoint
  stage: deploy
  script:
    - mc alias set minio $MINIO_HOST $MINIO_ACCESS_KEY $MINIO_SECRET_KEY
    - mc cp <source> <destination>
```

The GitLab documentation shows how you should [override the entrypoint](https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#overriding-the-entrypoint-of-an-image) in order for it to use a shell instead of the one in the image's Dockerfile. Note that this only works on Docker 17.06+.

It would be nice to have this in the README, so others don't have to go searching for this specific issue. I can put up a PR to add it in, but would need help with the Chinese translation.
