### ISSUE TITLE
Minio client mirror does not remove folders in watch mode

### ISSUE THREAD

**Issue by iamsimakov** [minio/mc#3375]
Minio is so cool and comfortable project, I like it. I'm very grateful to all contributors.

## Actual behavior and steps to reproduce

I start `docker-compose` with one storage and one minio client `mirror` in `--watch --remove` mode.
And after it I navigate to browser http://localhost:9001, create bucket `s3test` . (Maybe restart `docker-compose restart mc_sync` service because it could not see new bucket - check logs for `mc: <DEBUG> HTTP/1.1 200 OK`).

When `mc_sync` service is correctly started we can found bucket folder `s3test` in our `${PWD}/data_sync` - folder for synchronization.
I think it's ok - do not auto create bucket folder when we start `minio client mirror`.

Then I create new folder from admin panel, for example, `s3test/test_dir`.
There is no new folder on the disk of sync client - `${PWD}/data_sync/s3test/test_dir`. I think it's ok, because folder is emtpy.
Then I upload new file `file1.txt`, and it very fast synchronizes through minio client, and now folder of sync client is created `${PWD}/data_sync/s3test/test_dir`. 

Then I delete directory `s3test/test_dir` from admin panel in browser, but it's not deleted from disk of sync client.
When I remove `file1.txt` from admin panel - it's removed from disk of sync client, it works of course.

## Expected behavior

I think it's expected, when I delete folder, which containes files, from admin panel, it should be watched by `mc mirror --watch --remove` and folder should be deleted from disk of sync client.

In brief:
1) create dir A in admin panel
2) upload file in dir A
3) check that dir A is synching of mc mirror
4) delete dir A from admin panel
5) check that dir A is not deleted from disk of mc mirror

`docker-compose.yml`
```
version: '3.7'

services:
  minio1:
    image: minio/minio:RELEASE.2020-08-18T19-41-00Z
    volumes:
      - data1-1:/data1
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_BUCKET_MAIN: s3test
    command: server /data1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  mc_sync:
    image: minio/mc
    volumes:
      - '${PWD}/data_sync:/data'
      - '${PWD}/mc_config:/root/.mc'
    command: mirror --remove --preserve --watch --quiet --debug --json --no-color minio_cloud_store/s3test /data/s3test
```
`mc_config/config.json`

```
{
  "version": "9",
  "hosts": {
          "minio_cloud_store": {
                  "url": "http://minio1:9000",
                  "accessKey": "minio",
                  "secretKey": "minio123",
                  "api": "s3v4",
                  "lookup": "auto"
          }
  }
}
```

/ # mc --version
mc version RELEASE.2020-05-28T23-43-36Z

## System information
Ubuntu 18
