### ISSUE TITLE
mc sends unnecessary status messages to stdout when it's a TTY

### ISSUE THREAD

**Issue by kevinlul** [minio/mc#3499]
## Expected behavior
mc should behave consistently for testing so its output is parseable and informative logs shouldn't be in stdout but stderr

## Actual behavior
On a first run in a tty, mc dumps versions of this to stdout before the proper output of its command, even with `--json` and `--quiet`. This makes it difficult to test scripts reproducibly that expect structured output.

```
mc: Configuration written to `/root/.mc/config.json`. Please update your access credentials.
mc: Successfully created `/root/.mc/share`.
mc: Initialized share uploads `/root/.mc/share/uploads.json` file.
mc: Initialized share downloads `/root/.mc/share/downloads.json` file.
```

## Steps to reproduce the behavior

Example docker-compose
```yaml
version: "2"

services:
  minio:
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: docker
      MINIO_SECRET_KEY: inconsistent
    command: server /data
  mc:
    image: minio/mc
    environment:
      MC_HOST_app: http://docker:inconsistent@minio:9000
    depends_on:
      - minio
    command: admin --json user list app
```

`docker-compose up`: mc exits normally as expected, without any output
`docker-compose run --rm -T mc`: mc exits normally as expected, without any output since there is no TTY
`docker-compose run --rm mc`: mc dumps the above message to stdout

## mc --version
I found this to occur in
```
mc version RELEASE.2020-11-17T00-39-14Z
```
and
```
mc version RELEASE.2020-10-03T02-54-56Z
```

## System information
I've confirmed this to happen in Docker environments on WSL2, macOS, and Linux.
