### ISSUE TITLE
mirror --watch fail to sync new prefixed key

### ISSUE THREAD

**Issue by atroncy** [minio/mc#3913]
Hello,

We are currently evaluating the mc mirror --watch to keep insync two minio server.
We use the mirror on the fileSystemPath for the source, and the destination being a minio bucket. 
`mc mirror --watch /data/patients/ pca/patients` (pca being an alias for a remote minio server)

Overall the initial mirroring worked well, and the watch too expect for one situation.

When we add a new prefixed key in our bucket (on the src), the mirror seems to ignore it, if we had another key in the previously prefixed key it's not ignored and synced
eg: 

1) Given the bucket named /patients with the prefixed key 152061/...
  `patients/152061/test/key`
  `patients/152061/test3/key`

2) When we add a new key in the prefixed key 152061/test/key2
  `patients/152061/test/key2`
  The object is synced (as intended)
  
3) When we add a new prefixed key 152061/test2/key
   `patients/152061/test2/key`
 This object is not synced, somehow.

4) When we add a new key in the previously prefixed key 152061/test2/...
   `patients/152061/test2/key2`
   This object is synced, note that `patients/152061/test2/key` remains not synced.
   
We end up on our destination bucket with this synced
 `patients/152061/test/key`
 `patients/152061/test/key2`
 `patients/152061/test3/key`  
 `patients/152061/test2/key2`

Missing  this object  `patients/152061/test2/key`
   
We have been able to reproduce this multiples times, and it always does not sync the new prefixed key.

## Expected behavior
mc mirror --watch sync every new object regardless of being part of some new prefixed key 
## Actual behavior
mc mirror --watch sync fail to sync new object with new prefixed key
## Steps to reproduce the behavior
Put an object with a new prefixed key in an existing and synced bucket
## mc --version
- (paste output of `mc --version`)
mc version RELEASE.2021-12-10T00-14-28Z

**Comment by harshavardhana** [comment]
Does your filesystem support Inotify? @atroncy

**Comment by atroncy** [comment]
Hi @harshavardhana , I believe it do.

``` 
df -Th
Filesystem              Type     Size  Used Avail Use% Mounted on
/dev/sde                ext4     197G   74G  123G  38% /data
```

```
apiVersion: v1
kind: PersistentVolume
spec:
  accessModes:
  - ReadWriteOnce
  ...
  volumeMode: Filesystem
  vsphereVolume:
    fsType: ext4
    volumePath: '[VOLUME1_SAS_RAID5] kubevols/kubernetes-dynamic-pvc-e35c6524-a1d6-4637-af08-de1f04a06162.vmdk'
```
