### ISSUE TITLE
Memory leak when mirroring older minio servers.

### ISSUE THREAD

**Issue by chrisbecke** [minio/mc#3990]
## Expected behavior
The container version of minio/mc should use the available S3 APIs and mirror minio servers no matter their age.

## Actual behavior

The containerized version of mc eventially consumes all memory and is OOM killed by docker.

## Steps to reproduce the behavior

I am running an older minio server as a source server. It was installed circa 2020 and for regulatory reasons has not been updated. It is a simple minio in front of a single disk setup. 
The target minio instance is a 4 node cluster that is up-to-date.

I run mc as a docker container on docker swarm using this stack file:

```yml
version: "3.9"

configs:
  mc-2:
    file: .mc/config.json

networks:
  net:

services:
  sync-zfp-iob:
    image: minio/mc:latest
    command: >
      mirror
      --watch
      --monitoring-address=0.0.0.0:8080
      --quiet
      zfp/downloads
      iob/downloads
    networks:
      net:
    configs:
      - source: mc-2
        target: /root/.mc/config.json
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 1G
      restart_policy:
        max_attempts: 1
```

1. Prepar a .mc/config.json which contains an `iob` config pointing to a new minio instance and a `zfp` config pointing to an older - circa 2020 - minio instance. Have a "downloads" bucket on the old instance you want to mirror to the new instance.
2. `docker stack deploy --compose-file sync-stack.yml sync`
3. wait 30 minutes
4. `docker service ps sync_sync-zfp-iob`
5. It should be oom killed by docker by now.

## mc --version
- mc version RELEASE.2022-02-16T05-54-01Z

## Additional Info

Without the addition of `--watch` the command performs the mirror operation pretty flawlesslessly, but we need to mirror new content as it arrives. At any rate, if this operation is not supported, `mc` should fail outright, or log errors to the prometheus endpoint, NOT leak memory and die.
