### ISSUE TITLE
Admin service restart never completes

### ISSUE THREAD

**Issue by mymasse** [minio/mc#4043]
## Expected behaviour

Running `mc admin service restart minio` completes after restarting all nodes.

## Actual behaviour

Command never terminates (unless CTRL-C is used) and prints a '.' continuously.

## Steps to reproduce the behaviour

We run this from a script:

```
mc config host add minio $MC_URL $MC_ACCESS_KEY $MC_SECRET_KEY
mc admin config set minio notify_webhook:$NAME endpoint=$URL queue_dir=''
mc admin service restart minio
```

Script never terminates successfully.

## mc --version
- mc version RELEASE.2022-04-01T23-44-48Z

## System information

MinIO in Kubernetes

MinIO: RELEASE.2022-04-01T03-41-39Z
Deployed with MinIO Operator: 4.4.13

MinIO Tenant definition:
```
---yaml
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: tenant
  namespace: minio
  annotations:
    prometheus.io/path: /minio/v2/metrics/cluster
    prometheus.io/port: "9000"
    prometheus.io/scrape: "true"
spec:
  credsSecret:
    name: minio-secret
  requestAutoCert: false
  podManagementPolicy: Parallel
  image: minio/minio:RELEASE.2022-04-01T03-41-39Z
  env:
    - name: MINIO_BROWSER_REDIRECT_URL
      value: <REMOVED>
  pools:
    - servers: 4
      volumesPerServer: 1
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          storageClassName: default
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
      resources:
        requests:
          cpu: 250m
          memory: 500Mi
        limits:
          cpu: 1000m
          memory: 2Gi
      securityContext:
        fsGroup: 0
        runAsGroup: 0
        runAsNonRoot: false
        runAsUser: 0
  exposeServices:
    minio: false
```
