### ISSUE TITLE
Backup from self-hosted minio to S3 provider

### ISSUE THREAD

**Issue by giacomo-zanichelli** [minio/mc#4511]
## Expected behavior
I would like to deploy minio/mc in docker and use mc mirror once a day to backup my buckets to a different S3 provider

## Actual behavior
I have the following docker-compose snippet:

```
  minio:
    container_name: minio
    image: quay.io/minio/minio:RELEASE.2023-01-02T09-40-09Z
    command: server /data --console-address ":9001"
    user: ${MINIO_UID}:${MINIO_GID}
    restart: always
    security_opt:
      - no-new-privileges:true
    networks:
      - t2_proxy
      - backend_network
    volumes:
      - type: bind
        source: $APPDATA/minio/data
        target: /data
    secrets:
      - minio-root-user
      - minio-root-password
    environment:
      - MINIO_ROOT_USER_FILE=/run/secrets/minio-root-user
      - MINIO_ROOT_PASSWORD_FILE=/run/secrets/minio-root-password

      - MINIO_BROWSER_REDIRECT_URL=https://s3.$DOMAINNAME
 
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=t2_proxy"

      ## HTTP Routers
      - "traefik.http.routers.minio-rtr.entrypoints=https"
      - "traefik.http.routers.minio-rtr.rule=Host(`s3.$DOMAINNAME`)"
      - "traefik.http.routers.minio-rtr.tls=true"
      - "traefik.http.routers.minio-rtr.middlewares=chain-oidc@file"
      - "traefik.http.routers.minio-rtr.service=minio-svc"

      ## HTTP Services
      - "traefik.http.services.minio-svc.loadbalancer.server.port=9000"

  minio-mc:
    container_name: minio-mc
    image: minio/mc
    depends_on:
      - minio
    networks:
      - backend_network
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias minio-local <MINIO URL> <ACCESS KEY> <SECRET KEY>;
      /usr/bin/mc alias minio-remote <REMOTE PROVIDER> <ACCESS KEY> <SECRET KEY>;
      /usr/bin/mc mirror minio-local/bucket minio-remote/bucket;
      exit 0;
      "
```

The problem is that the minio-mc container exists after executing the entrypoint commands. Ideally I would like the container to keep running so that I can issue a mirror command once a day or so (outside of compose) for backing up my buckets.

Any other pointer on how to back up minio buckets from within docker would be appreciated. 

Thanks
