### ISSUE TITLE
Checksum Mismatch when querying with `LIKE`

### ISSUE THREAD

**Issue by jankap** [minio/mc#4521]
## Expected behavior
I have a test bucket containing 300 CSV files, ~100 MB in total. I'm querying and try to filter on some columns.
 
` ./mc sql --csv-input fd=";",fh="USE" --recursive --query "select * from s3Object s where s['Timestamp'] like '21.06.2021%'" local/test2/transientTemp/  --csv-output fd=";" > test.csv`

Test.csv should contain all rows with a Timestamp from 2021-06-21.

Using `./mc sql --csv-input fd=";",fh="USE" --recursive --query "select * from s3Object s where s['Timestamp'] like '21.06.2021 11:32:57'" local/test2/transientTemp/  --csv-output fd=";" > test.csv` works, so it seems to relate to the wildcard usage?

## Actual behavior

Error: mc.exe: <ERROR> Unable to run sql Checksum Mismatch, MessageCRC of 0x3B2D3435 does not equal expected CRC of 0xC9B3A800

The result file is not empty, but also does not contain all expected rows.

Is it possible to debug, e.g. find out which file creates

## mc --version
- (paste output of `mc --version`)
```
mc version RELEASE.2023-03-20T17-17-53Z (commit-id=88896ae495128646081d8f809b8934c74cb90194)
Runtime: go1.19.7 windows/amd64
Copyright (c) 2015-2023 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html
```

**Comment by klauspost** [comment]
Which server is this running against?

**Comment by jankap** [comment]
Latest MinIO Docker image.

**Comment by klauspost** [comment]
Thanks! I will see if I can reproduce. Pretty sure the issue either belongs in `minio` or `minio-go` repos, but let's keep it here until that is clear.

**Comment by klauspost** [comment]
My theory is that it is cutting off your response.

**Comment by klauspost** [comment]
My theory is that it is cutting off your response.

**Comment by jankap** [comment]
> My theory is that it is cutting off your response.

Very interesting. How did you debug that? And why does that not occur using no wildcard? Just due to the lower amount of data?

**Comment by klauspost** [comment]
@jankap The query takes longer with more files. The load balancer has some timeout configured (which it shouldn't) and it cuts off or writes some junk to the stream.

**Comment by jankap** [comment]
I increased the `proxy_connect_timeout` in nginx.conf to very high values - no difference.

Looking at the logs of nginx:
```
2023-03-30 20:16:42 172.19.0.1 - - [30/Mar/2023:18:16:42 +0000] "POST /test2/transientTemp/211600249_636609_cycling.csv?select=&select-type=2 HTTP/1.1" 200 6287557 "-" "MinIO (windows; amd64) minio-go/v7.0.49 mc.exe/RELEASE.2023-03-20T17-17-53Z" "-"
2023-03-30 20:16:42 172.19.0.1 - - [30/Mar/2023:18:16:42 +0000] "POST /test2/transientTemp/211600250_636609_cycling.csv?select=&select-type=2 HTTP/1.1" 200 1528037 "-" "MinIO (windows; amd64) minio-go/v7.0.49 mc.exe/RELEASE.2023-03-20T17-17-53Z" "-"
2023-03-30 20:16:42 172.19.0.1 - - [30/Mar/2023:18:16:42 +0000] "POST /test2/transientTemp/211600252_636609_cycling.csv?select=&select-type=2 HTTP/1.1" 200 300 "-" "MinIO (windows; amd64) minio-go/v7.0.49 mc.exe/RELEASE.2023-03-20T17-17-53Z" "-"
2023-03-30 20:16:42 172.19.0.1 - - [30/Mar/2023:18:16:42 +0000] "POST /test2/transientTemp/211600253_636609_cycling.csv?select=&select-type=2 HTTP/1.1" 200 6727508 "-" "MinIO (windows; amd64) minio-go/v7.0.49 mc.exe/RELEASE.2023-03-20T17-17-53Z" "-"
2023-03-30 20:16:42 172.19.0.1 - - [30/Mar/2023:18:16:42 +0000] "POST /test2/transientTemp/211600254_636609_cycling.csv?select=&select-type=2 HTTP/1.1" 200 300 "-" "MinIO (windows; amd64) minio-go/v7.0.49 mc.exe/RELEASE.2023-03-20T17-17-53Z" "-"
2023-03-30 20:16:42 172.19.0.1 - - [30/Mar/2023:18:16:42 +0000] "POST /test2/transientTemp/211600256_636609_cycling.csv?select=&select-type=2 HTTP/1.1" 200 6131955 "-" "MinIO (windows; amd64) minio-go/v7.0.49 mc.exe/RELEASE.2023-03-20T17-17-53Z" "-"
```

The files broken are the ones with 6xxxxxx Bytes transferred.

There are no messages in the minio log/stdout.

BTW, my environment is currently Docker on my local PC. docker-compose and nginx.config below.
Is there anything I can test?

Thanks!

docker-compose.yaml:
```
version: '3.7'

# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: quay.io/minio/minio:latest
  command: server --address ":9000" --console-address ":9991" /minio/data1
  expose:
    - "9000"
    - "9991"
  environment:
    MINIO_ROOT_USER: jan
    MINIO_ROOT_PASSWORD: "xxx"
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9999/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3

# starts ~4~ 1 docker containers running minio server instances.
# using nginx reverse proxy, load balancing, you can access
# it through port 9000.
services:
  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - data1-1:/data1
      - data1-2:/data2

  nginx:
    image: nginx:latest
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
    # see https://github.com/compose-spec/compose-spec/blob/master/spec.md#ports
      - "127.0.0.1:9999:9999"
      - "127.0.0.1:9991:9991"
    depends_on:
      - minio1
#       - minio2
#       - minio3
#       - minio4

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  data1-1:
  data1-2:
  data2-1:
  data2-2:
  data3-1:
  data3-2:
  data4-1:
  data4-2:
```

config:
```
user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections  4096;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;
    sendfile        on;
    keepalive_timeout  65;

    # include /etc/nginx/conf.d/*.conf;

    upstream minio {
        server minio1:9000;
        # server minio2:9000;
        # server minio3:9000;
        # server minio4:9000;
    }

    upstream console {
        ip_hash;
        server minio1:9991;
        # server minio2:9991;
        # server minio3:9991;
        # server minio4:9991;
    }

    server {
        listen       9999;
        listen  [::]:9999;
        server_name  localhost;

        # To allow special characters in headers
        ignore_invalid_headers off;
        # Allow any size file to be uploaded.
        # Set to a value such as 1000m; to restrict file size to a specific value
        client_max_body_size 0;
        # To disable buffering
        proxy_buffering off;
        proxy_request_buffering off;

        location / {
            # restrict access
            # does not work here, because everything goes through the docker host ip, even external requests, due do NAT/Bridge

            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_connect_timeout 300000;
            # Default is HTTP/1, keepalive is only enabled in HTTP/1.1
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            chunked_transfer_encoding off;

            proxy_pass http://minio;
        }
    }

    server {
        listen       9991;
        listen  [::]:9991;
        server_name  localhost;

        # To allow special characters in headers
        ignore_invalid_headers off;
        # Allow any size file to be uploaded.
        # Set to a value such as 1000m; to restrict file size to a specific value
        client_max_body_size 0;
        # To disable buffering
        proxy_buffering off;
        proxy_request_buffering off;

        location / {
            # restrict access
            # allow 172.16.0.0/12; # docker network 172.16.0.0/12 IP addresses: 172.16.0.0 – 172.31.255.255, DONT DO THAT! It allows full acess
            # does not work here, because everything goes through the docker host ip, even external requests, due do NAT/Bridge

            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-NginX-Proxy true;

            # This is necessary to pass the correct IP to be hashed
            real_ip_header X-Real-IP;

            proxy_connect_timeout 300000;

            # To support websocket
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";

            chunked_transfer_encoding off;

            proxy_pass http://console;
        }
    }
}
```
