### ISSUE TITLE
Checksum mismatch when download latest mc binary file

### ISSUE THREAD

**Issue by ct-jby** [minio/mc#4527]
## Expected behavior

When downloading the latest mc binary (example: https://dl.min.io/client/mc/release/linux-amd64/mc), the checksum succeeds.

## Actual behavior

When downloading the latest mc binary (example: https://dl.min.io/client/mc/release/linux-amd64/mc), the checksum fails because the checksum file contains the binary name of the complete release.

For example the file mc.sha256sum contains the file name "mc.RELEASE.xxxx-xxTxx-xx-xxZ" instead of "mc"

![image](https://user-images.githubusercontent.com/108006482/228510664-b575bc6c-2f8b-4469-b60f-2de55b93d87e.png)

### Ansible playbook:

context -->  Deploy the mc client on servers, virtual workstations or locally

The example playbook below allows to deploy the mc client locally

```yaml
---
- hosts: localhost
  connection: local
  become: true
  tasks:
   - name: Download minio client binary file with checksum (sha256)
     get_url:
        url: "https://dl.min.io/client/mc/release/linux-amd64/mc"
        dest: "/usr/local/bin/mc"
        checksum: "sha256:https://dl.min.io/client/mc/release/linux-amd64/mc.sha256sum"
        mode: '0755'
```

### Manually:

download files:
- https://dl.min.io/client/mc/release/linux-amd64/mc
- https://dl.min.io/client/mc/release/linux-amd64/mc.sha256sum

do checksum control
