### ISSUE TITLE
minio fails to mirror between two buckets properly

### ISSUE THREAD

**Issue by jaceknoga** [minio/mc#4644]
## Expected behavior
Data between two mc mirror deployments should be consistent. 

## Actual behavior
Data is inconsistent. Attached setup simulates `development` environment which makes some writes randomly to local storage on Docker container (`data-generator`). 
This storage is synced then via `mc mirror` command in separate container (`data-mirror-first`) to MinIO bucket on [play.min.io](https://play.min.io:9443/browser/).
Another container (`buckets-sync`) acts as a continous actor to sync changes between two remote buckets and last, which seems to work properly while using `mc cp` or adding files via Browser console.
To simulate some filesystem changes I've add `random-data-first-delete` container which occasionally removes data from local storage and `random-data-first-copy` which copies files from local storage to first bucket directly (instead of using `mirror -- watch`) and which works flawlessly.

For logging and debugging purposes I've added:
- `bucket-first-watch` which acts as mc watch for first bucket
- `bucket-second-watch` which acts as mc watch for second bucket
- `bucket-first-trace-errors` which acts as mc admin trace error for first bucket
- `bucket-second-trace-errors` which acts as mc admin trace error for second bucket

## Steps to reproduce the behavior
Basically it's better to produce `docker-compose.yaml` for testing and evaluating purposes. Please see below.

I've also added environment variables to check if object locking or versioning does make any change.

Whole setup should create and remove needed buckets on MinIO's play site.

After running for a few seconds data in second bucket is totally different than first bucket. 

Some facts:
- Data from local storage to first bucket is correctly mirrored.
- Data from first bucket to second bucket is synced properly only at startup or after restarting `buckets-sync` container and only works once after restart.
- Uploading data via Browser console to first bucket works correctly and data is mirrored to second bucket via `buckets-sync` container (altough without any logs) correclty and constantly.
- Data in second bucket gets out of sync almost instantly.

```shell
MB_ADDITIONAL_ARGS="--with-lock --with-versioning"
MIRROR_ADDITIONAL_ARGS="--disable-multipart --newer-than 5d"
```

```yaml
version: '3.9'

name: "mc-s3-sync-test"

volumes:
  data:
  data-mirrored:

x-service-defaults: &x-service-defaults
  image: minio/mc:RELEASE.2023-07-21T20-44-27Z
  restart: until-stopped
  working_dir: /data
  stop_grace_period: "5s"
  deploy:
    restart_policy:
      condition: on-failure
      delay: 15s
      max_attempts: 15
      window: 120s

services:
  data-generator:
    <<: *x-service-defaults
    volumes:
      - data:/data
    entrypoint: ["/bin/bash", "-c"]
    command: >
        'trap "mc rb -q --force --no-color --force play/rq2ph6t; mc rb -q --force --no-color --force play/3wskq6q; exit" EXIT SIGHUP SIGINT SIGTERM;
        mc mb ${MB_ADDITIONAL_ARGS:-} -p --no-color play/rq2ph6t;
        mc mb ${MB_ADDITIONAL_ARGS:-} -p --no-color play/3wskq6q;
        i=0;
        while :; do 
          head -c $$(seq 32 4096 | sort -R | head -n 1) /dev/urandom | base64 > /data/$$i.txt && echo "Updated $$i.txt file.";
          sync;
          ((i+=1));
          [ "$$i" -ge 5 ] && i=0 && echo "Pausing a loop for 5 seconds." && sleep 5 || sleep 2;
        done;'

  data-mirror-first:
    <<: *x-service-defaults
    volumes:
      - data:/data:ro
    entrypoint: ["/bin/bash", "-c"]
    command: >
      'trap "exit" EXIT SIGHUP SIGINT SIGTERM;
      mc mb ${MB_ADDITIONAL_ARGS:-} -p --no-color play/rq2ph6t;
      mc mirror ${MIRROR_ADDITIONAL_ARGS:-} --watch --overwrite --remove --preserve --md5 --no-color /data play/rq2ph6t'

  buckets-sync:
    <<: *x-service-defaults
    volumes:
      - data:/data:ro
    entrypoint: ["/bin/bash", "-c"]
    command: >
      'trap "exit" EXIT SIGHUP SIGINT SIGTERM;
      mc mb ${MB_ADDITIONAL_ARGS:-} -p --no-color play/rq2ph6t;
      mc mb ${MB_ADDITIONAL_ARGS:-} -p --no-color play/3wskq6q;
      mc mirror ${MIRROR_ADDITIONAL_ARGS:-} --watch --overwrite --remove --preserve --md5 --no-color play/rq2ph6t play/3wskq6q'

  bucket-first-watch:
    <<: *x-service-defaults
    entrypoint: ["/bin/bash", "-c"]
    command: >
      'trap "exit" EXIT SIGHUP SIGINT SIGTERM;
      mc mb ${MB_ADDITIONAL_ARGS:-} -p --no-color play/rq2ph6t;
      mc watch --no-color --recursive play/rq2ph6t'

  bucket-second-watch:
    <<: *x-service-defaults
    entrypoint: ["/bin/bash", "-c"]
    command: >
      'trap "exit" EXIT SIGHUP SIGINT SIGTERM;
      mc mb ${MB_ADDITIONAL_ARGS:-} -p --no-color play/3wskq6q;
      mc watch --no-color --recursive play/3wskq6q'

  bucket-first-trace-errors:
    <<: *x-service-defaults
    command: admin trace -e --path rq2ph6t/* play

  bucket-second-trace-errors:
    <<: *x-service-defaults
    command: admin trace -e --path 3wskq6q/* play

  random-data-first-delete:
    <<: *x-service-defaults
    volumes:
      - data:/data
    entrypoint: ["/bin/bash", "-c"]
    command: >
      'trap "exit" EXIT SIGHUP SIGINT SIGTERM;
      sleep 3;
      while :; do
        sleep_time=$$(seq 4 15 | sort -R | head -n 1);
        i=$$(seq 0 4 | sort -R | head -n 1);
        echo "Pausing a loop for $$sleep_time seconds." && sleep $$sleep_time;
        [ -f /data/$$i.txt ] && rm /data/$$i.txt && echo "Removed $$i.txt file.";
      done;'

  random-data-first-copy:
    <<: *x-service-defaults
    volumes:
      - data:/data:ro
    entrypoint: ["/bin/bash", "-c"]
    command: >
      'trap "exit" EXIT SIGHUP SIGINT SIGTERM;
      sleep 3;
      while :; do
        sleep_time=$$(seq 10 30 | sort -R | head -n 1);
        i=$$(seq 0 4 | sort -R | head -n 1);
        [ -f /data/$$i.txt ] && mc cp -q --no-color /data/$$i.txt play/rq2ph6t && echo "Pausing a loop for $$sleep_time seconds." && sleep $$sleep_time || sleep 1;
      done;'

  data-mirror-second:
    <<: *x-service-defaults
    volumes:
      - data-mirrored:/data
    entrypoint: ["/bin/bash", "-c"]
    command: >
      'trap "exit" EXIT SIGHUP SIGINT SIGTERM;
      mc mb ${MB_ADDITIONAL_ARGS:-} -p --no-color play/3wskq6q;
      mc mirror ${MIRROR_ADDITIONAL_ARGS:-} play/3wskq6q /data --watch --overwrite --remove  --md5 --preserve'
```

## mc --version
- (paste output of `mc --version`)
```shell
mc version RELEASE.2023-07-21T20-44-27Z (commit-id=1c17ff4c995d772c97eed8c5a269f2074a9425fe)
Runtime: go1.19.11 linux/amd64
Copyright (c) 2015-2023 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
```

I've tested above `docker-compose.yaml` with some random versions (above 2022-01-01) from Docker Hub and behavior seems to be the same.

## System information
Tested on play.min.io instance and with Docker instances running on macOS and Debian as well.

play.min.io instance:
```json
{
  "state": "online",
  "endpoint": "play.min.io",
  "version": "2023-07-22T00:30:04Z",
  "commitID": "e1094dde08f310ea2fbbd2b368c6d2c189a2ff70"
}
```
