### ISSUE TITLE
mc mirror data inconsistent vs bucket replication

### ISSUE THREAD

**Issue by jaceknoga** [minio/mc#4646]
## Expected behavior
Data between two mc mirror endpoints and replicatied bucket should be consistent.
@harshavardhana please review this issue thoroughly once again, thank You.

## Actual behavior
Data is inconsistent. 

There are 5 actors:
- `data-generator` which generates random data,
- `data-generator-mirror` which mirrors random data from above to `rq2ph6t` bucket,
- `bucket1-to-bucket2-mirror` which mirrors  (via `mc mirror`)`rq2ph6t` bucket to `3wskq6q` bucket,
- `random-data-first-delete` which deletes files randomly from `data-generator` volume to simulate regular environment,
- `random-data-first-copy` which copies (`mc cp`) data from `data-generator` volume to `rq2ph6t` bucket.

There's a replication set for `rq2ph6t` bucket which replicates all actions (without hard delete) to `rq2ph6t-replica` bucket.

To prove data incosistency there's a sidecar `lister` which list all buckets and volumes content.

After a few minutes, data in part of above volumes is inconsistent.

Some facts:
- Data from local storage to `rq2ph6t` bucket is correctly mirrored.
- Data from `rq2ph6t` bucket to `3wskq6q` bucket is synced properly only at startup or after restarting `bucket1-to-bucket2-mirror` container and only works once after restart. Same behavior while using `mc` without Docker containers.
- Uploading data via browser Console to `rq2ph6t` bucket works correctly and data is mirrored to `3wskq6q` bucket via `bucket1-to-bucket2-mirror` container (altough without any logs) correctly and constantly.
- Data in `3wskq6q` bucket gets out of sync almost instantly.
- Data in replicated bucket (`rq2ph6t-replica`) is consistent.

Please compare logs below:
```sh
test-lister-1  | ### Listing header
test-lister-1  | /source-data listing:
test-lister-1  | 0.txt	2023-07-25T10:02:12.888172634Z	640b	
test-lister-1  | 1.txt	2023-07-25T10:02:14.916172756Z	4936b	
test-lister-1  | 2.txt	2023-07-25T10:02:16.945602073Z	2308b	
test-lister-1  | 3.txt	2023-07-25T10:02:18.975602195Z	2860b	
test-lister-1  | 4.txt	2023-07-25T10:02:21.005602317Z	2892b	

test-lister-1  | myminio/rq2ph6t bucket listing:
test-lister-1  | 0.txt	2023-07-25T10:02:12.89Z		640b	28e7ca8064ea55f0845fefcacc5f0f92
test-lister-1  | 1.txt	2023-07-25T10:02:14.919Z	4936b	24e769cf1a413fd2bfa18a7f3ce98c3d
test-lister-1  | 2.txt	2023-07-25T10:02:16.949Z	2308b	b21d3446229a9b481db7bc15242fb188
test-lister-1  | 3.txt	2023-07-25T10:02:18.978Z	2860b	7fabf6bbc6cb5042de5ee5858f68beb9
test-lister-1  | 4.txt	2023-07-25T10:02:21.009Z	2892b	745f6b3481d5319ee574df48d44c7c2e

test-lister-1  | myminio/rq2ph6t-replica bucket listing:
test-lister-1  | 0.txt	2023-07-25T10:02:12.89Z		640b	28e7ca8064ea55f0845fefcacc5f0f92
test-lister-1  | 1.txt	2023-07-25T10:02:14.919Z	4936b	24e769cf1a413fd2bfa18a7f3ce98c3d
test-lister-1  | 2.txt	2023-07-25T10:02:16.949Z	2308b	b21d3446229a9b481db7bc15242fb188
test-lister-1  | 3.txt	2023-07-25T10:02:18.978Z	2860b	7fabf6bbc6cb5042de5ee5858f68beb9
test-lister-1  | 4.txt	2023-07-25T10:02:21.009Z	2892b	745f6b3481d5319ee574df48d44c7c2e

test-lister-1  | myminio/3wskq6q bucket listing:
test-lister-1  | 0.txt	2023-07-25T09:59:22.021Z	700b	a56734beaecf459dbe6aa78249737502
test-lister-1  | 1.txt	2023-07-25T10:01:44.926Z	4824b	2d7371a568699730cded43fd68de235f
test-lister-1  | 3.txt	2023-07-25T10:01:20.795Z	2388b	26f46fa9d14080131a2dbd8344303abf
test-lister-1  | 4.txt	2023-07-25T10:02:15.069Z	3968b	60aa45dd05fa121c2c06135d843e5b0a

test-lister-1  | /mirrored-data1 (mc mirror from myminio/3wskq6q) listing:
test-lister-1  | 0.txt	2023-07-25T09:58:42.562629615Z	4196b	
test-lister-1  | 1.txt	2023-07-25T09:58:47.55232911Z	776b	

test-lister-1  | /mirrored-data2 (mc mirror from myminio/rq2ph6t-replica) listing:
test-lister-1  | 0.txt	2023-07-25T09:58:42.562629615Z	4196b	
test-lister-1  | 1.txt	2023-07-25T09:58:47.535329109Z	776b	
test-lister-1  | 2.txt	2023-07-25T09:58:46.632329055Z	1276b	
test-lister-1  | ### Listing footer
```

Please do some restarts for mirror containers (`data-mirror1` and `data-mirror2`) to observe further changes.

It seems that somehow changes from local storage are not synced between two remote buckets, but data uploaded via browser Console is. Changes from buckets are not synced then via mirror to local storage neither.

## Steps to reproduce the behavior
Basically it's better to produce `docker-compose.yaml` for testing and evaluating purposes. Please see below.

Just let it run for minute or two and monitor `lister` container (`docker-compose logs -f lister`) for output changes.

```yaml
version: '3.9'

name: "test"

volumes:
  server-data:
  source-data:
  mirrored-data1:
  mirrored-data2:

x-service-defaults: &x-service-defaults
  image: minio/mc:RELEASE.2023-07-21T20-44-27Z
  restart: until-stopped
  working_dir: /data
  stop_grace_period: "5s"
  environment:
    MINIO_ACCESS_KEY: doesntmatter
    MINIO_SECRET_KEY: doesntmattereither
    MB_ADDITIONAL_ARGS: "--with-lock --with-versioning"
    MIRROR_ADDITIONAL_ARGS: "--active-active"
    LS_ADDITIONAL_ARGS: ""
    JQ_ARGS: '. | [.key, .lastModified, (.size | tostring + "b"), .etag] | @tsv'
  deploy:
    restart_policy:
      condition: on-failure
      delay: 15s
      max_attempts: 15
      window: 120s
  depends_on:
    - data-generator

x-server-defaults: &x-server-defaults
  <<: *x-service-defaults
  image: minio/minio:RELEASE.2023-07-21T21-12-44Z
  command: ['server', '/data', '--console-address', ':9090']
  environment:
    MINIO_ROOT_USER: doesntmatter
    MINIO_ROOT_PASSWORD: doesntmattereither
    MINIO_BROWSER: "on"
  depends_on: []

services:
  minio-server1:
    <<: *x-server-defaults
    volumes:
      - server-data:/data
    ports:
      - 9090:9090
      - 9000:9000

  data-generator:
    <<: *x-service-defaults
    volumes:
      - source-data:/data
    entrypoint: ["/bin/bash", "-c"]
    command: >
        'trap "mc rb -q --force --no-color --force myminio/rq2ph6t; mc rb -q --force --no-color --force myminio/3wskq6q; mc rb -q --force --no-color --force myminio/rq2ph6h-replica; rm -rf /data/* exit" EXIT SIGHUP SIGINT SIGTERM;
        mc alias set myminio http://minio-server1:9000 $${MINIO_ACCESS_KEY} $${MINIO_SECRET_KEY};
        mc mb $${MB_ADDITIONAL_ARGS:-} -p --no-color myminio/rq2ph6t;
        mc mb $${MB_ADDITIONAL_ARGS:-} -p --no-color myminio/3wskq6q;
        mc mb $${MB_ADDITIONAL_ARGS:-} -p --no-color myminio/rq2ph6t-replica;
        mc replicate add myminio/rq2ph6t --remote-bucket http://$${MINIO_ACCESS_KEY}:$${MINIO_SECRET_KEY}@minio-server1:9000/rq2ph6t-replica --replicate ""delete-marker,existing-objects,metadata-sync"" --priority 1;
        i=0;
        while :; do 
          head -c $$(seq 32 4096 | sort -R | head -n 1) /dev/urandom | base64 -w 0 > /data/$${i}.txt && echo "Updated $${i}.txt file.";
          sync;
          ((i+=1));
          [ "$${i}" -ge 5 ] && i=0 && echo "Pausing a loop for 5 seconds." && sleep 5 || sleep 2;
        done;'
    depends_on:
      - minio-server1

  data-generator-mirror:
    <<: *x-service-defaults
    volumes:
      - source-data:/data:ro
    entrypoint: ["/bin/bash", "-c"]
    command: >
      'trap "exit" EXIT SIGHUP SIGINT SIGTERM;
      mc alias set myminio http://minio-server1:9000 $${MINIO_ACCESS_KEY} $${MINIO_SECRET_KEY};
      mc mirror --watch --overwrite --remove --preserve --md5 --no-color /data myminio/rq2ph6t'

  bucket1-to-bucket2-mirror:
    <<: *x-service-defaults
    volumes:
      - source-data:/data:ro
    entrypoint: ["/bin/bash", "-c"]
    command: >
      'trap "exit" EXIT SIGHUP SIGINT SIGTERM;
      mc alias set myminio http://minio-server1:9000 $${MINIO_ACCESS_KEY} $${MINIO_SECRET_KEY};
      mc mirror $${MIRROR_ADDITIONAL_ARGS:-} --watch --overwrite --remove --preserve --md5 --no-color myminio/rq2ph6t myminio/3wskq6q'

  bucket1-watch:
    <<: *x-service-defaults
    entrypoint: ["/bin/bash", "-c"]
    command: >
      'trap "exit" EXIT SIGHUP SIGINT SIGTERM;
      mc alias set myminio http://minio-server1:9000 $${MINIO_ACCESS_KEY} $${MINIO_SECRET_KEY};
      mc watch --no-color --recursive myminio/rq2ph6t'

  bucket2-watch:
    <<: *x-service-defaults
    entrypoint: ["/bin/bash", "-c"]
    command: >
      'trap "exit" EXIT SIGHUP SIGINT SIGTERM;
      mc alias set myminio http://minio-server1:9000 $${MINIO_ACCESS_KEY} $${MINIO_SECRET_KEY};
      mc watch --no-color --recursive myminio/3wskq6q'

  bucket1-replica-watch:
    <<: *x-service-defaults
    entrypoint: ["/bin/bash", "-c"]
    command: >
      'trap "exit" EXIT SIGHUP SIGINT SIGTERM;
      mc alias set myminio http://minio-server1:9000 $${MINIO_ACCESS_KEY} $${MINIO_SECRET_KEY};
      mc watch --no-color --recursive myminio/rq2ph6t-replica'

  admin-trace:
    <<: *x-service-defaults
    entrypoint: ["/bin/bash", "-c"]
    command: >
      'trap "exit" EXIT SIGHUP SIGINT SIGTERM;
      mc alias set myminio http://minio-server1:9000 $${MINIO_ACCESS_KEY} $${MINIO_SECRET_KEY};
      mc admin trace myminio'

  random-data-first-delete:
    <<: *x-service-defaults
    volumes:
      - source-data:/data
    entrypoint: ["/bin/bash", "-c"]
    command: >
      'trap "exit" EXIT SIGHUP SIGINT SIGTERM;
      mc alias set myminio http://minio-server1:9000 $${MINIO_ACCESS_KEY} $${MINIO_SECRET_KEY};
      sleep 3;
      while :; do
        sleep_time=$$(seq 4 15 | sort -R | head -n 1);
        i=$$(seq 0 4 | sort -R | head -n 1);
        echo "Pausing a loop for $$sleep_time seconds." && sleep $$sleep_time;
        [ -f /data/$$i.txt ] && rm /data/$$i.txt && echo "Removed $$i.txt file.";
      done;'

  random-data-first-copy:
    <<: *x-service-defaults
    volumes:
      - source-data:/data:ro
    entrypoint: ["/bin/bash", "-c"]
    command: >
      'trap "exit" EXIT SIGHUP SIGINT SIGTERM;
      mc alias set myminio http://minio-server1:9000 $${MINIO_ACCESS_KEY} $${MINIO_SECRET_KEY};
      sleep 3;
      while :; do
        sleep_time=$$(seq 10 30 | sort -R | head -n 1);
        i=$$(seq 0 4 | sort -R | head -n 1);
        [ -f /data/$$i.txt ] && mc cp -q --no-color /data/$$i.txt myminio/rq2ph6t && echo "Pausing a loop for $$sleep_time seconds." && sleep $$sleep_time || sleep 1;
      done;'

  data-mirror1:
    <<: *x-service-defaults
    volumes:
      - mirrored-data1:/data
    entrypoint: ["/bin/bash", "-c"]
    command: >
      'trap "exit" EXIT SIGHUP SIGINT SIGTERM;
      mc alias set myminio http://minio-server1:9000 $${MINIO_ACCESS_KEY} $${MINIO_SECRET_KEY};
      sleep 5;
      mc mirror $${MIRROR_ADDITIONAL_ARGS:-} --watch --overwrite --remove myminio/3wskq6q /data'

  data-mirror2:
    <<: *x-service-defaults
    volumes:
      - mirrored-data2:/data
    entrypoint: ["/bin/bash", "-c"]
    command: >
      'trap "exit" EXIT SIGHUP SIGINT SIGTERM;
      mc alias set myminio http://minio-server1:9000 $${MINIO_ACCESS_KEY} $${MINIO_SECRET_KEY};
      sleep 5;
      mc mirror $${MIRROR_ADDITIONAL_ARGS:-} --watch --overwrite --remove myminio/rq2ph6t-replica /data'
  
  lister:
    <<: *x-service-defaults
    volumes:
      - source-data:/source-data:ro
      - mirrored-data1:/mirrored-data1:ro
      - mirrored-data2:/mirrored-data2:ro
    entrypoint: ["/bin/bash", "-c"]
    command: >
      'trap "exit" EXIT SIGHUP SIGINT SIGTERM;
      mc alias set myminio http://minio-server1:9000 $${MINIO_ACCESS_KEY} $${MINIO_SECRET_KEY};
      sleep 2;
      while :; do
        echo "### Listing header";
        echo "/source-data listing:";
        mc ls --json --quiet --no-color /source-data | jq -r "$${JQ_ARGS}";

        echo "myminio/rq2ph6t bucket listing:";
        mc ls --json --quiet --no-color myminio/rq2ph6t | jq -r "$${JQ_ARGS}";

        echo "myminio/rq2ph6t-replica bucket listing:";
        mc ls --json --quiet --no-color myminio/rq2ph6t-replica | jq -r "$${JQ_ARGS}";

        echo "myminio/3wskq6q bucket listing:";
        mc ls --json --quiet --no-color myminio/3wskq6q | jq -r "$${JQ_ARGS}";

        echo "/mirrored-data1 (mc mirror from myminio/3wskq6q) listing:";
        mc ls --json --quiet --no-color /mirrored-data1 | jq -r "$${JQ_ARGS}";

        echo "/mirrored-data2 (mc mirror from myminio/rq2ph6t-replica) listing:";
        mc ls --json --quiet --no-color /mirrored-data2 | jq -r "$${JQ_ARGS}";

        echo "### Listing footer";
        sleep 15;
      done;'
```

## mc --version
- (paste output of `mc --version`)
```shell
mc version RELEASE.2023-07-21T20-44-27Z (commit-id=1c17ff4c995d772c97eed8c5a269f2074a9425fe)
Runtime: go1.19.11 linux/amd64
Copyright (c) 2015-2023 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
```

Server side:
```shell
minio version RELEASE.2023-07-21T21-12-44Z (commit-id=d004c4538643eb05ea69b919557d5cf7cc332fae)
Runtime: go1.19.11 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2023 MinIO, Inc.
```

I've tested above `docker-compose.yaml` with some random versions (above 2022-01-01) from Docker Hub and behavior seems to be the same.

## System information
Tested on play.min.io instance and with Docker instances running on macOS and Debian as well.

Local Docker instance:
```json
{
  "state": "online",
  "endpoint": "minio-server1:9000",
  "version": "2023-07-21T21:12:44Z",
  "commitID": "d004c4538643eb05ea69b919557d5cf7cc332fae"
}
```
