### ISSUE TITLE
minio-make-user job in community helm chart broken

### ISSUE THREAD

**Issue by opencmit2** [minio/mc#4764]
## Expected behavior
The image used in the previous minio-make-user job included the sed command.

## Actual behavior

since changing the base image of the mc container image from ubi-minimal to ubi-micro (minio/mc#4725), the make-user step in the community helm chart is broken when using an existing secret for credentials, as the step uses sed, which is not included in ubi-micro.

## mc --version
- (paste output of `mc --version`)
```yaml
mcImage:
  repository: quay.io/minio/mc
  tag: RELEASE.2023-09-29T16-41-22Z
```
