### ISSUE TITLE
can't upload `.zip` file in minio

### ISSUE THREAD

**Issue by maifeeulasad** [minio/mc#4844]
## Expected behavior

It should be able to upload a `zip` without any issues

## Actual behavior

It throws lots of error. It gives me: `mc: <ERROR> Unable to prepare URL for copying. To copy or move '/html-admin.zip' the --recursive flag is required.`.  Even if I set the flag `-r` or `--recursive`. Then it gives me `mc: <ERROR> Unable to prepare URL for copying. To copy or move './zip/html-admin.zip' the --recursive flag is required.`
## Steps to reproduce the behavior
```yml
version: '3.6'

services:
  ...
  store-s3-admin:
    image: minio/mc
    entrypoint: ["/bin/sh", "-c"]
    volumes:
      - ./html-admin.zip:/html-admin.zip
    command: ["mc alias set minio https://files.mydomain.bd xxx yyy && mc cp /html-admin.zip minio/report/html-admin.zip"]
    depends_on:
      zipper-admin:
        condition: service_completed_successfully
```

## mc --version
- `Runtime: go1.21.6 linux/amd64`

## System information
```
  buildx*     Docker Buildx (Docker Inc., v0.11.2-desktop.5)
  compose*    Docker Compose (Docker Inc., v2.22.0-desktop.2)
  dev*        Docker Dev Environments (Docker Inc., v0.1.0)
  extension*  Manages Docker extensions (Docker Inc., v0.2.20)
  init*       Creates Docker-related starter files for your project (Docker Inc., v0.1.0-beta.8)
  sbom*       View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan*       Docker Scan (Docker Inc., v0.26.0)
  scout*      Docker Scout (Docker Inc., v1.0.7)
```
