### ISSUE TITLE
mc admin prometheus generate - YAML indentation

### ISSUE THREAD

**Issue by FLAK-ZOSO** [minio/mc#5214]
## Premise

This is more of a feature proposal/request, not a bug. It could be a bug in case this feature was already intended.

## Expected behavior

```yaml
scrape_configs:
  - job_name: minio-job-node
    bearer_token: eyJh...
    metrics_path: /minio/v2/metrics/node
    scheme: http
    static_configs:
    - targets: ['localhost:9000']
```

## Actual behavior

Notice the indentation.

```yaml
scrape_configs:
- job_name: minio-job-node
  bearer_token: eyJh...
  metrics_path: /minio/v2/metrics/node
  scheme: http
  static_configs:
  - targets: ['localhost:9000']
```

Would be very handy for those automating the Prometheus setup to directly have valid YAML, or just having to replace `localhost` with a FQDN rather than having to deal with automation of indentation (for those knowing Ansible, it can be a hustle).

## Steps to reproduce the behavior
```
/usr/local/bin/mc admin prometheus generate minio1 node
```

```
mc version RELEASE.2025-05-21T01-59-54Z (commit-id=f71ad84bcf0fd4369691952af5d925347837dcec)
Runtime: go1.24.3 linux/amd64
Copyright (c) 2015-2025 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
```

## System information

Just a BASH, nothing more.

```
Linux invenio-mattia 6.8.0-60-generic #63-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 15 19:04:15 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
```
